# Generated by Django 3.0.5 on 2020-06-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sunset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('experiences', models.ManyToManyField(to='main_app.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.CharField(choices=[('5', '5 stars'), ('4', '4 stars'), ('3', '3 stars'), ('2', '2 stars'), ('1', '1 star')], default='5', max_length=1)),
                ('sunset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sunset')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
